<div id="footer">
<hr />
<a href=".">Proè</a> | <a href="http://proc.linux.cz/vyhody.html">Vyhody</a> | <a href="chci-vyzkouset.html">Chci vyzkou¹et</a> | <a href="kde-ziskat.html">Kde získat</a>
<hr />
(c) 2005 -
<?php echo date('Y') ?>&nbsp;
<a href="http://sandbox.cz/~covex/">Adam Pøibyl</a>, <a href="mailto:proc@linux.cz">e-mail</a> - <a href="http://www.linux.cz/">pod zá¹titou CZLUG</a>
</div>
<!-- Google Code for PAGEVIEW Conversion Page -->
<script language="JavaScript" type="text/javascript">
<!--
var google_conversion_id = 1069089218;
var google_conversion_language = "cs";
var google_conversion_format = "1";
var google_conversion_color = "FFFFFF";
if (1) {
  var google_conversion_value = 1;
}
var google_conversion_label = "PAGEVIEW";
//-->
</script>
<script language="JavaScript" src="http://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<img height=1 width=1 border=0 src="http://www.googleadservices.com/pagead/conversion/1069089218/?value=1&label=PAGEVIEW&script=0">
</noscript>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-1091564-2";
urchinTracker();
</script>
