<img class="doprava" src="img/stit.png" title="" alt="" />

<h1><img class="unadpisu" src="img/bezpecnost.png" alt="" />&nbsp;Bezpeènost</h1>

<p>
Doby, kdy jste se museli bát o svá data, jsou pryè. Do va¹eho <span class="linux">Linuxu</span> se jen tak nìkdo nepovolaný nedostane. ®ádný vir ani spyware vám nebude probírat po¹tu a nìkomu ji posílat, kdy¾ nechcete. Budete mnohem bezpeènìj¹í pøed
útoky na vá¹ bankovní úèet i bez ¹íleného firewallu - i kdy¾ i <b>firewall</b> <span class="linux">Linux</span> má, ale v podstatì ho neuvidíte. Pracuje samostatnì a bez obtì¾ování. To v¹echno máte v <b>plné verzi a bez registrace</b>. Nikdo nemusí vìdìt, ¾e pou¾ívate
<span class="linux">Linux</span>, pokud se nebudete sami chtít pochlubit. <a href="?vzhled">A ¾e je èím</a>.
</p>
<p>
Va¹e dokumenty, fotografie i hudba jsou na disku pod dohledem <span class="linux">Linuxu</span> v bezpeèí a nepo¹kodí je ani bì¾né problémy jako je výpadek proudu.
</p>
<p class="historie">
Bezpeèí systému se dá dìlat dvìma cestami. Z principu nebo omalovánkami. Krabice ale va¹e data neochrání. <span class="linux">Linux</span> na bezpeènosti stojí od základu a vyvinul se proto, aby byl bezpeèný. Obsahoval firewall ji¾ 
v dobì, kdy o nìm jiní je¹tì nezaèali ani uva¾ovat.
</p>
