<div class="doprava">
<a href="img/ff2.png">
<img width="220" height="171" src="img/ff2_t.png" title="Firefox" alt="" />
</a>
<div class="popisek">Webový prohlí¾eè Firefox</div>
</div>

<h1><img class="unadpisu" src="img/internet.png" alt="" />&nbsp;Internet</h1>

<p>
Myslíte si, ¾e znáte Internet? Vyzkou¹ejte jak vypadá v <span class="linux">Linuxu</span>. S <a href="http://www.mozilla.cz/produkty/firefox/">Firefoxem</a>. A pokud Firefox u¾ znáte, není nic jednodu¹¹ího ne¾ si svá nastavení, hesla a zálo¾ky <a href="/prevod-dat.html">pøevést do <span class="linux">Linuxu</span></a>.
<br />
V¹echny novinky mù¾ete mít na dosah s RSS stejnì jako døíve vèetnì svojí po¹ty z <a href="http://www.mozilla.cz/produkty/thunderbird">Thunderbirdu</a>. Své pøátele opìt najdete pomocí kecálka <a href="http://www.pidgin.im/">Pidgin</a> nebo <a href="http://skype.com/intl/en/download/skype/linux/">Skype</a>. A jako bonus dostanete <a href="?bezpecnost">bezpeèí</a> a <a href="?vzhled">jedineèný vzhled</a>.
</p>
<p class="historie">
Internet, jak ho znáte, zaèal Netscapem. I ten be¾el na <span class="linux">Linuxu</span>, ale poskytoval jen málo z toho, co dnes znáte. Jen díky pricipùm <span class="linux">Linuxu</span> se ale Netscape vyvinul do dne¹ního Firefoxu. I Firefox je toti¾ svobodný software stejnì jako celý <span class="linux">Linux</span>.
</p>




