<div class="doprava">
<a href="img/listen.png">
<img width="220" height="171" src="img/listen_t.png" title="Audio knihovna Listen" alt="" />
</a>
<div class="popisek">Audio knihovna Listen</div>
</div>

<h1><img class="unadpisu" src="img/multimedia.png" alt="" />&nbsp;Multimédia</h1>


<p>
Mìli jste nìkdy problémy s pøehráváním nìjakého filmu? Chybìl vám kodek, nebo prostì pøehrávaè
odmítl daný formát pøehrát? Pak byste mìli zkusit linuxový <a href="http://www.mplayerhq.hu/design7/news.html">MPlayer</a> (The Movie Player).
</p>
<p>
Organizaci své sbírky hudby (a» u¾ v <b>mp3</b> nebo jiných formátech) pøenechte nìkterému z linuxových programù. Stejnì tak byste mìli zkusit, jak
snadno dáte øád v¹em svým fotografiím.
</p>
<p>
Staèí jen vybrat nìkterý z dostupných programù, který vám vyhovuje, a nainstalovat. Nebo prostì pou¾ijte to, co pro
vás distributoøi peèlivì vybrali. <u>®ádné zdlouhavé pøebírání shareware, ¾ádné trial verze.</u>
</p>

<p class="historie">
<span class="linux">Linux</span> nevyrostl jako multimediální systém, dnes v¹ak bez problému zvládá v¹echny oblasti
multimediální zábavy, ale i mnohem víc. A tak je pou¾íván i ve filmových studiích.
</p>
