<div class="doprava">
<a href="img/listen.png">
<img width="220" height="171" src="img/listen_t.png" title="Audio knihovna Listen" alt="" />
</a>
<div class="popisek">Audio knihovna Listen</div>
</div>

<h1><img class="unadpisu" src="img/multimedia.png" alt="" />&nbsp;Multimédia</h1>


<p>
Měli jste někdy problémy s přehráváním nějakého filmu? Chyběl vám kodek, nebo prostě přehrávač
odmítl daný formát přehrát? Pak byste měli zkusit linuxový <a href="http://www.mplayerhq.hu/design7/news.html">MPlayer</a> (The Movie Player).
</p>
<p>
Organizaci své sbírky hudby (ať už v <b>mp3</b> nebo jiných formátech) přenechte některému z linuxových programů. Stejně tak byste měli zkusit, jak
snadno dáte řád všem svým fotografiím.
</p>
<p>
Stačí jen vybrat některý z dostupných programů, který vám vyhovuje, a nainstalovat. Nebo prostě použijte to, co pro
vás distributoři pečlivě vybrali. <u>Žádné zdlouhavé přebírání shareware, žádné trial verze.</u>
</p>

<p class="historie">
<span class="linux">Linux</span> nevyrostl jako multimediální systém, dnes však bez problému zvládá všechny oblasti
multimediální zábavy, ale i mnohem víc. A tak je používán i ve filmových studiích.
</p>
