<div class="doprava">
<a href="img/gmenu.png"><img width="220" height="126" src="img/gmenu_t.png" title="GNOME menu" alt="" /></a>
<div class="popisek">Menu GNOME</div>
</div>

<h1><img class="unadpisu" src="img/ovladani.png" alt="" />&nbsp;Ovládání</h1>
<p>
Přistupujte k ovládání <span class="linux">Linuxu</span> s intuicí a ne návyky. Brzy pochopíte, že ovládat váš systém může být mnohem jednodušší.
Navíc v <span class="linux">Linuxu</span> máte nespočet možností, jak si chování svého systému nastavit.
</p>
<p>
A kancelářské aplikace? Ty jsou dnes už běžnou součástí <span class="linux">Linuxu</span>. Třeba v podobě <a href="http://www.libreoffice.cz/">LibreOffice</a>.
</p>

<p class="historie">Linuxové vyhledávání a indexování fungovalo již v dobách, kdy se <span class="linux">Linux</span> používal nejčastěji s textovým
výstupem, a pod nánosem moderních prvků ho můžete nalézt jako příkaz <tt>locate</tt>. Dnes ale můžete vyzkoušet i moderní nástroje jako
<a href="http://projects.gnome.org/tracker/index.html">Gnome Tracker</a>.
</p>