<div class="doprava">
<a href="img/gmenu.png"><img width="220" height="126" src="img/gmenu_t.png" title="GNOME menu" alt="" /></a>
<div class="popisek">Menu GNOME</div>
</div>

<h1><img class="unadpisu" src="img/ovladani.png" alt="" />&nbsp;Ovládání</h1>
<p>
Pøistupujte k ovládání <span class="linux">Linuxu</span> s intuicí a ne návyky. Brzy pochopíte, ¾e ovládat vá¹ systém mù¾e být mnohem jednodu¹¹í.
Navíc v <span class="linux">Linuxu</span> máte nespoèet mo¾ností, jak si chování svého systému nastavit.
</p>
<p>
A kanceláøské aplikace? Ty jsou dnes u¾ bì¾nou souèástí <span class="linux">Linuxu</span>. Tøeba v podobì <a href="http://www.libreoffice.cz/">LibreOffice</a>.
</p>

<p class="historie">Linuxové vyhledávání a indexování fungovalo ji¾ v dobách, kdy se <span class="linux">Linux</span> pou¾íval nejèastìji s textovým
výstupem, a pod nánosem moderních prvkù ho mù¾ete nalézt jako pøíkaz <tt>locate</tt>. Dnes ale mù¾ete vyzkou¹et i moderní nástroje jako
<a href="http://projects.gnome.org/tracker/index.html">Gnome Tracker</a>.
</p>