<h1><img class="unadpisu" src="img/svoboda.png" alt="" />&nbsp;Svoboda</h1>
<p>
Do nedávna jste si svùj operaèní systém vybrat nemohli. Museli jste pou¾ívat buï Windows a nebo... Windows. Dnes máte na výbìr <span class="linux">Linux</span>. Vyzkou¹ejte si svobodu
prostøedí, které vám nic nediktuje a nikde nepøeká¾í. Dìlá to, co potøebujete, a vy mù¾ete dìlat to, co chcete.
</p>
<p>
Za v¹echno se ale "platí". V pøípadì <span class="linux">Linuxu</span> ale jen va¹í chutí uèit se a poznávat netu¹ené mo¾nosti. <a href="/kde-ziskat.html">Tak do toho</a>.
</p>

<p class="historie">
<span class="linux">Linux</span> se zaèal vyvíjet v roce 1991 jako jádro systému Unixového typu. Posléze byl pou¾it jako základ kompletního OS
tvoøeného linuxovým jádrem a programy projektu GNU. Od té doby je <span class="linux">Linux</span> svobodným volnì dostupným operaèním systémem.
</p>
