<div class="doprava">
<a href="img/beryl.jpg"><img width="220" height="171" src="img/beryl_t.png" title="3D pøepínání desktopù" alt="" /></a> 
<div class="popisek">3D pøepínání desktopu</div>
</div>

<h1><img class="unadpisu" src="img/vzhled.png" alt="" />&nbsp;Vzhled</h1>
<ul>
<li>prùhlednost</li>
<li>grafické efekty</li>
<li>okna ve 3D prostoru</li>
<li>¾ivé náhledy</li> 
</ul>
<p>
- to je jen výbìr z toho, co <span class="linux">Linux</span> u¾ nejaký ten pátek umí. Stále se zlep¹uje a nepotøebujete k tomu supermoderní poèítaè.
</p>
<p>
<a href="http://youtube.com/results?search_query=xgl+OR+aiglx&search=Search">Podívejte se</a> sami, jak <span class="linux">Linux</span> dnes vypadá a co doká¾í jeho okna ovládaná <a href="http://www.compiz.org/">Compizem</a>.
</p>

<p class="historie">
Jako je mo¾né mìnit celý <span class="linux">Linux</span>, je mo¾né mìnit i jeho vzhled. A je tomu tak u¾ mnoho let. <span class="linux">Linux</span> má nespoèetnì podob a barev pleti. Stejnì jako lidé, kteøí ho pou¾ívají. 
Pøeneste si vzhled svého pokoje i na monitor.
</p>